# VIA_ENABLE				 	= yes

#[HARDWARE FEATURES]
BOOTMAGIC_ENABLE			= yes
RGBLIGHT_ENABLE				= yes
RAW_ENABLE					= yes
COMMAND_ENABLE				= no
CONSOLE_ENABLE				= no
LTO_ENABLE					= no
NKRO_ENABLE					= no

ENCODER_ENABLE				= no
ENCODER_MAP_ENABLE			= no

#[SOFTWARE FEATURES]
ENABLE_CHORDAL_HOLD			= yes
AUTOCORRECT_ENABLE			= no

DYNAMIC_KEYMAP_ENABLE		= no
DYNAMIC_MACRO_ENABLE		= no

#[ADVANCED KEYCODES]
COMBO_ENABLE 				= yes
UNICODE_COMMON 				= yes
EXTRAKEY_ENABLE 			= yes
CAPS_WORD_ENABLE 			= yes
REPEAT_KEY_ENABLE 			= yes
LAYER_LOCK_ENABLE 			= yes
SEND_STRING_ENABLE			= yes
KEY_OVERRIDE_ENABLE			= no
SPACE_CADET_ENABLE 			= no
GRAVE_ESC_ENABLE 			= no
TAP_DANCE_ENABLE 			= no
MOUSEKEY_ENABLE				= no

#[EXTRA FEATURES]
#[GETREUER]
CUSTOM_SHIFT_KEYS_ENABLE	= yes
ORBITAL_MOUSE_ENABLE		= yes
SELECT_WORD_ENABLE			= yes
KEYCODE_STRING_ENABLE		= no

ROOT_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
include ${ROOT_DIR}../../../../../rules.mk
